#!/bin/bash

echo "digite um número:"
read V
if test "$V" -gt 10
then
  echo "maior que 10"
else
  echo "menor que 10"
fi

if [ "$V" -gt 10 ]
then
  echo "maior que 10"
else
  echo "menor que 10"
fi



